#!/usr/bin/env node
// Generate the README skill catalogue and the plugin marketplace skill lists
// from each skill's frontmatter, so neither can drift from the skills.
//
//   node tools/catalogue.mjs           # rewrite README.md and .claude-plugin/marketplace.json
//   node tools/catalogue.mjs --check   # exit 1 if either is stale (CI)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { splitFrontmatter, parseFrontmatter } from './lib/frontmatter.mjs';

const START = '<!-- catalogue:start -->';
const END = '<!-- catalogue:end -->';

export const MARKETPLACE_BASE = {
  name: 'vidmoat-skills',
  owner: { name: 'Vidmoat', url: 'https://github.com/vidmoat' },
  description: 'Open video-editing craft as Agent Skills: captions, audio, colour, pacing and more. Works with any editor or with ffmpeg.',
};

export const PLUGINS = {
  core: {
    name: 'vidmoat-core',
    displayName: 'Vidmoat core skills',
    description: 'Maintainer-curated video editing skills with evals. The only set Vidmoat production loads.',
    category: 'video',
    tags: ['video', 'editing', 'captions', 'audio', 'skills'],
  },
  community: {
    name: 'vidmoat-community',
    displayName: 'Vidmoat community skills',
    description: 'Community-contributed video editing skills. Linted and reviewed, but not loaded by Vidmoat production; install deliberately.',
    category: 'video',
    tags: ['video', 'editing', 'community', 'skills'],
  },
};

export function readSkills(root) {
  const out = [];
  for (const tier of ['core', 'community']) {
    const dir = path.join(root, 'skills', tier);
    if (!fs.existsSync(dir)) continue;
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!ent.isDirectory()) continue;
      const md = path.join(dir, ent.name, 'SKILL.md');
      if (!fs.existsSync(md)) continue;
      const { data } = parseFrontmatter(splitFrontmatter(fs.readFileSync(md, 'utf8')).raw);
      out.push({
        tier,
        folder: ent.name,
        name: String(data.name ?? ent.name),
        description: String(data.description ?? '').trim(),
        version: String(data.metadata?.version ?? ''),
      });
    }
  }
  return out.sort((a, b) => a.tier.localeCompare(b.tier) || a.name.localeCompare(b.name));
}

function firstSentence(text, max = 180) {
  const flat = text.replace(/\s+/g, ' ').trim();
  const m = /^(.+?[.!?])(\s|$)/.exec(flat);
  let s = m ? m[1] : flat;
  if (s.length > max) s = s.slice(0, max - 3).replace(/\s+\S*$/, '') + '...';
  return s.replace(/\|/g, '\\|');
}

export function renderCatalogue(skills) {
  const lines = [START, '', '_Generated by `npm run catalogue` from each SKILL.md. Do not edit by hand._', ''];
  for (const tier of ['core', 'community']) {
    const rows = skills.filter((s) => s.tier === tier);
    lines.push(`**${tier === 'core' ? 'Core (maintainer-curated)' : 'Community'}**`, '');
    if (!rows.length) {
      lines.push(tier === 'community' ? '_No community skills yet. See [CONTRIBUTING.md](CONTRIBUTING.md) to propose one._' : '_None yet._', '');
      continue;
    }
    lines.push('| Skill | Version | What it does |', '| --- | --- | --- |');
    for (const s of rows) {
      lines.push(`| [\`${s.name}\`](skills/${tier}/${s.folder}/SKILL.md) | ${s.version || 'n/a'} | ${firstSentence(s.description)} |`);
    }
    lines.push('');
  }
  lines.push(END);
  return lines.join('\n');
}

export function renderMarketplace(skills) {
  const plugins = [];
  for (const tier of ['core', 'community']) {
    const rows = skills.filter((s) => s.tier === tier);
    if (!rows.length) continue; // an empty plugin is noise in /plugin listings
    plugins.push({
      name: PLUGINS[tier].name,
      displayName: PLUGINS[tier].displayName,
      description: PLUGINS[tier].description,
      source: './',
      strict: false,
      category: PLUGINS[tier].category,
      tags: PLUGINS[tier].tags,
      skills: rows.map((s) => `./skills/${tier}/${s.folder}`),
    });
  }
  return JSON.stringify({ ...MARKETPLACE_BASE, plugins }, null, 2) + '\n';
}

export function applyCatalogue(readme, skills) {
  const s = readme.indexOf(START);
  const e = readme.indexOf(END);
  if (s === -1 || e === -1 || e < s) throw new Error(`README.md must contain ${START} and ${END} markers`);
  return readme.slice(0, s) + renderCatalogue(skills) + readme.slice(e + END.length);
}

function main() {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const check = process.argv.includes('--check');
  const skills = readSkills(root);
  const readmePath = path.join(root, 'README.md');
  const mpPath = path.join(root, '.claude-plugin', 'marketplace.json');
  const readme = fs.readFileSync(readmePath, 'utf8').replace(/\r\n/g, '\n');
  const nextReadme = applyCatalogue(readme, skills);
  const nextMp = renderMarketplace(skills);
  const curMp = fs.existsSync(mpPath) ? fs.readFileSync(mpPath, 'utf8').replace(/\r\n/g, '\n') : '';
  if (check) {
    const stale = [];
    if (nextReadme !== readme) stale.push('README.md');
    if (nextMp !== curMp) stale.push('.claude-plugin/marketplace.json');
    if (stale.length) {
      console.error(`Stale: ${stale.join(', ')}. Run "npm run catalogue" and commit the result.`);
      process.exit(1);
    }
    console.log(`Catalogue is fresh (${skills.length} skill(s)).`);
    return;
  }
  fs.writeFileSync(readmePath, nextReadme);
  fs.mkdirSync(path.dirname(mpPath), { recursive: true });
  fs.writeFileSync(mpPath, nextMp);
  console.log(`Wrote README.md catalogue and marketplace.json (${skills.length} skill(s)).`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
